### ISSUE TITLE
Share the prebuilt jar file here

### ISSUE THREAD

**Issue by ildar** [dmarszk/hummingbird-hibl#5]
Please, put in "releases". Thanks

**Comment by ouzza** [comment]
pleasse share the prebuilt .jar filles

**Comment by Meticulus** [comment]
Found 1 copy of R40 HERE
https://www.4shared.com/file/1Gx6ZSXjei/UnBrickableResurrectorR40.html

**Comment by dmarszk** [comment]
I just uploaded R41 binaries.
