### ISSUE TITLE
Use BL1_stage1.bin with uboot

### ISSUE THREAD

**Issue by PabloPL** [dmarszk/hummingbird-hibl#6]
Hi
Could You give a hint how to append BL1_stage1.bin to uboot (there is some WIP for aries family https://github.com/xc-racer99/u-boot-galaxys4g) ?

Since i9000 and galaxy s 4g are coming into mainline (patches got accepted), it would be nice to have uboot running on it (instead of stock bootloaders).

**Comment by adamoutler** [comment]
It gets directly appended.  We had a script to combine and create a disk but it is apparently lost.

**Comment by PabloPL** [comment]
Closing this "issue" as we have uboot spl support WIP.
