### ISSUE TITLE
How to start hummingbird-hibl?

### ISSUE THREAD

**Issue by TuxFanGKR** [dmarszk/hummingbird-hibl#7]
Hello!
My netbook (32bit) run Ubuntu Mate 16.04 with openjdk java 8 runtime. I download the .zip file from repository. How can i compile or start the program. I found no .jar file in the repo. I have no java knowledge.
I try to rename the zip file to hummingbird-hibl.jar and set file to executable but i can't start with java 8 runtime. What is the solution.
Please help.
With kind regards
TuxFanGKR

**Comment by ildar** [comment]
https://github.com/dmarszk/hummingbird-hibl/releases ?

**Comment by TuxFanGKR** [comment]
@ildar Thanks for Help. I forget to look at releases.
